server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB.URL}:3306/MiniProject?useSSL=false&serverTimezone=UTC

    username: ${DB.ID}
    password: ${DB.PWD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 17276671958-9vosc7h6umjin28gce3lehb52r9etena.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://tr1ll1on.site/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: name, email, profile
          kakao:
            client-id: d16d27af8c80f006b20243d792d81319
            redirect-uri: https://tr1ll1on.site/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
          naver:
            client-id: DbN0tWPpERMTMHksWDB5
            client-secret: TrPMZUJEwB
            redirect-uri: https://tr1ll1on.site/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: nickname, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springdoc:
  api-docs:
    path: /v1/api-docs
    groups:
      enabled: true
  packages-to-scan: com.ybe.tr1ll1on.domain
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false

logging:
  level:
    org.springframework.security: DEBUG
