server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://miniproject.cwwqogbd32f8.us-east-2.rds.amazonaws.com:3306/MiniProject?useSSL=false&serverTimezone=UTC
    username: ${DB.ID}
    password: ${DB.PWD}

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false

