

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://trillion.cv5i1mslgh5q.ap-northeast-2.rds.amazonaws.com:3306/MiniProject?useSSL=false&serverTimezone=UTC

    username: ${{ secrets.DB_ID }}
    password: ${{ secrets.DB_PWD }}

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false